# Generated by Django 6.1.1 on 2026-09-24 04:17

import fuinoise_live.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuinoise_live", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_time_zone",
            field=models.CharField(
                choices=fuinoise_live.models.timezone_choices,
                default="US/Pacific",
                max_length=80,
                verbose_name="Time zone that is considered the home timezone for the event",
            ),
        ),
    ]
