# Generated by Django 6.1.1 on 2026-09-24 05:38

import django.db.models.deletion
from django.db import migrations, models

import fuinoise_live.models


class Migration(migrations.Migration):

    dependencies = [
        ("fuinoise_live", "0004_streamer_twitch_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="")),
                ("logo_url", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "communities",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="raidslot",
            name="handoff_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Planned raid handoff time; leave blank until known",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="streamer",
            name="organizer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="streamer",
            name="raid_availability",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("open", "Open to raids"),
                    ("limited", "Ask first"),
                    ("unavailable", "Unavailable"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="streamer",
            name="raid_preferences",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="streamer",
            name="time_zone",
            field=models.CharField(
                choices=fuinoise_live.models.timezone_choices,
                default="UTC",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="community",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="fuinoise_live.community",
            ),
        ),
        migrations.CreateModel(
            name="CommunityMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, default="", max_length=80)),
                ("joined_on", models.DateField(blank=True, null=True)),
                ("organizer_notes", models.TextField(blank=True, default="")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fuinoise_live.community",
                    ),
                ),
                (
                    "streamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fuinoise_live.streamer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="streamer",
            name="communities",
            field=models.ManyToManyField(
                blank=True,
                related_name="streamers",
                through="fuinoise_live.CommunityMembership",
                to="fuinoise_live.community",
            ),
        ),
        migrations.AddField(
            model_name="streamer",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="streamers", to="fuinoise_live.genre"
            ),
        ),
        migrations.AddField(
            model_name="streamer",
            name="instruments",
            field=models.ManyToManyField(
                blank=True, related_name="streamers", to="fuinoise_live.instrument"
            ),
        ),
        migrations.CreateModel(
            name="WeeklyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "end_time",
                    models.TimeField(
                        help_text="In the streamer's time zone; may be on the next day"
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "streamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_availability",
                        to="fuinoise_live.streamer",
                    ),
                ),
            ],
            options={
                "ordering": ("streamer_id", "day_of_week", "start_time", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="communitymembership",
            constraint=models.UniqueConstraint(
                fields=("community", "streamer"),
                name="unique_community_streamer_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyavailability",
            constraint=models.UniqueConstraint(
                fields=("streamer", "day_of_week", "start_time"),
                name="unique_streamer_weekly_start",
            ),
        ),
    ]
