# Generated by Django 6.1.1 on 2026-09-24 05:54

import fuinoise_live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuinoise_live", "0006_backfill_event_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("private", "Private"),
                ],
                default="draft",
                help_text="Only published events appear on the public site.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_time_zone",
            field=models.CharField(
                choices=fuinoise_live.models.timezone_choices,
                default="GMT",
                max_length=80,
                verbose_name="Time zone that is considered the home timezone for the event",
            ),
        ),
    ]
