# Generated by Django 6.1.1 on 2026-09-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuinoise_live", "0007_event_publication_status_alter_event_event_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raidslot",
            name="streamer",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for an open time slot; change this to move a streamer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fuinoise_live.streamer",
            ),
        ),
    ]
