# Generated by Django 6.1.1 on 2026-09-24 06:29

import fuinoise_live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuinoise_live', '0008_alter_raidslot_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='default_time_zone',
            field=models.CharField(choices=fuinoise_live.models.timezone_choices, default='GMT', max_length=80, verbose_name='Default raid event time zone'),
        ),
    ]
