# Generated by Django 6.1.1 on 2026-09-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fuinoise_live", "0010_alter_streamer_display_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raidslot",
            name="handoff_at",
        ),
    ]
