# Generated by Django 6.1.1 on 2026-09-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuinoise_live', '0011_remove_raidslot_handoff_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raidslot',
            options={'ordering': ['event_id', 'start', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='raidslot',
            name='unique_raid_slot_event_position',
        ),
        migrations.RemoveField(
            model_name='raidslot',
            name='position',
        ),
        migrations.AddConstraint(
            model_name='raidslot',
            constraint=models.UniqueConstraint(fields=('event', 'start'), name='unique_raid_slot_event_start'),
        ),
    ]
