# Generated by Django 6.1.1 on 2026-10-05 01:09

import django.core.validators
import django.db.models.deletion
import fuinoise_live.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuinoise_live', '0012_alter_raidslot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('replay_url', models.URLField(blank=True, default='')),
                ('raid_slot_note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('start', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('base_schedule_version', models.PositiveIntegerField(editable=False)),
                ('base_fingerprint', models.CharField(editable=False, max_length=64)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('event_time_zone', models.CharField(choices=fuinoise_live.models.timezone_choices, max_length=80)),
                ('default_slot_duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('signup_before_publication', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='default_slot_duration_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='signup_before_publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raidslot',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Planned length. Older slots need duration review before publishing.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('default_slot_duration_minutes__gt', 0)), name='event_positive_default_duration'),
        ),
        migrations.AddConstraint(
            model_name='raidslot',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='slot_positive_duration'),
        ),
        migrations.AddField(
            model_name='draftslot',
            name='source_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuinoise_live.raidslot'),
        ),
        migrations.AddField(
            model_name='draftslot',
            name='streamer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuinoise_live.streamer'),
        ),
        migrations.AddField(
            model_name='scheduledraft',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuinoise_live.community'),
        ),
        migrations.AddField(
            model_name='scheduledraft',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_draft', to='fuinoise_live.event'),
        ),
        migrations.AddField(
            model_name='draftslot',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fuinoise_live.scheduledraft'),
        ),
        migrations.AddConstraint(
            model_name='scheduledraft',
            constraint=models.CheckConstraint(condition=models.Q(('default_slot_duration_minutes__gt', 0)), name='draft_positive_default_duration'),
        ),
        migrations.AddConstraint(
            model_name='draftslot',
            constraint=models.UniqueConstraint(fields=('draft', 'source_slot'), name='draft_unique_source_slot'),
        ),
        migrations.AddConstraint(
            model_name='draftslot',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gt', 0), _connector='OR'), name='draft_slot_positive_duration'),
        ),
    ]
