# Generated by Django 6.1.1 on 2026-10-05 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuinoise_live', '0013_draftslot_scheduledraft_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('discord_username', models.CharField(blank=True, default='', max_length=80)),
                ('discord_member', models.BooleanField(blank=True, null=True)),
                ('discord_guild_id', models.CharField(blank=True, default='', max_length=32)),
                ('discord_checked_at', models.DateTimeField(blank=True, null=True)),
                ('participation_status', models.CharField(choices=[('pending', 'Awaiting organizer review'), ('approved', 'Approved'), ('declined', 'Not approved')], default='pending', max_length=16)),
                ('discord_override', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='fuinoise_live.streamer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='streamer_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_eligibility', 'Can review streamer participation'), ('override_discord_requirement', 'Can override Discord requirement')],
            },
        ),
        migrations.CreateModel(
            name='EligibilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('participation_status', models.CharField(max_length=16)),
                ('discord_override', models.BooleanField()),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fuinoise_live.streameraccount')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
