# Generated by Django 6.1.1 on 2026-10-05 01:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuinoise_live', '0014_streameraccount_eligibilityreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftslot',
            name='request_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted for review'), ('withdrawn', 'Withdrawn'), ('declined', 'Not approved')], default='submitted', max_length=16)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('organizer_notes', models.TextField(blank=True, default='', max_length=2000)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_requests', to='fuinoise_live.event')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_requests', to='fuinoise_live.streamer')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SlotPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start', models.DateTimeField()),
                ('requested_duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferences', to='fuinoise_live.raidslot')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='fuinoise_live.slotrequest')),
            ],
            options={
                'ordering': ('requested_start', 'id'),
            },
        ),
        migrations.AddField(
            model_name='draftslot',
            name='signup_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_slots', to='fuinoise_live.slotrequest'),
        ),
        migrations.AddField(
            model_name='raidslot',
            name='signup_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_slots', to='fuinoise_live.slotrequest'),
        ),
        migrations.AddConstraint(
            model_name='slotrequest',
            constraint=models.UniqueConstraint(fields=('event', 'streamer'), name='unique_event_streamer_request'),
        ),
        migrations.AddConstraint(
            model_name='slotpreference',
            constraint=models.UniqueConstraint(fields=('request', 'slot'), name='unique_request_preferred_slot'),
        ),
        migrations.AddConstraint(
            model_name='slotpreference',
            constraint=models.CheckConstraint(condition=models.Q(('requested_duration_minutes__gt', 0)), name='preference_positive_duration'),
        ),
    ]
