# Generated by Django 6.1.1 on 2026-10-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuinoise_live', '0015_draftslot_request_version_slotrequest_slotpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=25)),
                ('display_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('profile_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('profile_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_live', models.BooleanField(blank=True, null=True)),
                ('status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('stream_title', models.CharField(blank=True, default='', max_length=500)),
                ('game_name', models.CharField(blank=True, default='', max_length=200)),
                ('stream_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_error', models.CharField(blank=True, default='', max_length=255)),
                ('streamer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_snapshot', to='fuinoise_live.streamer')),
            ],
        ),
    ]
